AWSTemplateFormatVersion: 2010-09-09
Description: cfn-init demo
Parameters:
  InstanceType:
    Type: String
    AllowedValues:
      - t2.micro
      - t3.micro
      - m3.large
    Default: 't2.micro'
  ExportStackName:
    Type: String
    Default: 'VPC-CFN'

Resources:
  EC2DemoInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: 'ami-02fe204d17e0189fb'
      SecurityGroupIds:
        - Fn::ImportValue: !Sub "${ExportStackName}-SecurityGroupId"
      SubnetId:
        Fn::ImportValue: !Sub "${ExportStackName}-PublicSubnetId"
      Tags:
        - Key: 'Name'
          Value: 'demo-ec2-instance'
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/bash -xe
          yum update -y aws-cfn-bootstrap
          # cfn-init
          /opt/aws/bin/cfn-init -s ${AWS::StackId} -r EC2DemoInstance --region ${AWS::Region}
          # wait condition
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource DemoWaitCondition --region ${AWS::Region}
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
          files:
            "/var/www/html/index.html":
              content: |
                <h1>Hello AWS User Group Lviv</h1>
              mode: '000644'
          services:
            sysvinit:
              httpd:
                enabled: 'true'
                ensureRunning: 'true'
  DemoWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    CreationPolicy:
      ResourceSignal:
        Timeout: PT2M
