AWSTemplateFormatVersion: 2010-09-09
Description: Demo import values
Parameters:
  ExportStackName:
    Type: String
    Default: 'VPC-CFN'
  InstanceType:
    Type: String
    AllowedValues:
      - t2.micro
      - t3.micro
      - m3.large
    Default: 't2.micro'

Resources: 
  DemoEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: 'ami-02fe204d17e0189fb'
      SecurityGroupIds:
        - Fn::ImportValue: !Sub "${ExportStackName}-SecurityGroupId"
      SubnetId: 
        Fn::ImportValue: !Sub "${ExportStackName}-PublicSubnetId"
      Tags:
        - Key: 'Name'
          Value: 'demo-ec2-instance'

Outputs:
  Ec2Id:
    Description: EC2 Instance Id
    Value: !Ref DemoEC2
    Export:
      Name: !Sub "${AWS::StackName}-InstanceId"